#![cfg(unix)]

//! E2E-C: a legacy six-tool SessionRecord with a historical `subagent`
//! exchange and a legal auxiliary record. The removed executor is gone, so the
//! Session is listable/readable, `turn.result` and `tool.output` still answer,
//! `session.open` is refused before execution, the bytes are never rewritten,
//! and a fresh five-tool Session still runs.
//!
//! The fixture bytes below were generated by the real Store and History types
//! (see the 0916 closeout acceptance record), not hand-written JSON.

use std::path::PathBuf;

use serde_json::{Value, json};

#[path = "support/openai_mock.rs"]
mod openai_mock;
#[path = "support/rpc_process.rs"]
mod rpc_process;
use openai_mock::{MockResponse, MockServer};
use rpc_process::RpcProcess;

const KEY_ENV: &str = "MINICORE_E2E_C_TEST_KEY";
const KEY: &str = "e2e-c-fixture-secret";

const SESSION_ID: &str = "ses_2a24b985622325826b336d25e6750499";
const LOOP_ID: &str = "lup_960347f4f796126a9cc17809e53094a4";
const TOOL_CALL_ID: &str = "legacy-subagent-call";
const AUX_HASH: &str = "6366c852f562f07dd57c0f45d901c2588adc12d8b2da12d96b4970ad1c5d8d34";

const SESSION_JSON_TEMPLATE: &str = r#"{"format_version":1,"session_id":"__SESSION__","title":"legacy six","profile":"test","workspace":"__WORKSPACE__","model":"main","reasoning":"auto","system_prompt":"test system prompt","tools":["read","subagent"],"max_tool_rounds":8,"approval":"auto","created_at":"2026-01-02T03:04:05.000Z","updated_at":"2026-01-02T03:04:05.000Z"}"#;

const HISTORY_JSONL: &str = r#"{"loop_id":"lup_960347f4f796126a9cc17809e53094a4","outcome":{"type":"completed"},"items":[{"type":"user","data":{"loop_id":"lup_960347f4f796126a9cc17809e53094a4","kind":"prompt","input":{"text":"delegate this"}}},{"type":"assistant","data":{"loop_id":"lup_960347f4f796126a9cc17809e53094a4","request_index":0,"model":"main","reasoning":"auto","content":[{"type":"tool_call","data":{"tool_call_id":"legacy-subagent-call","name":"subagent","arguments":{"task":"historical child"},"call_index":0}}],"finish_reason":"tool_calls","usage":{"input_tokens":1,"output_tokens":2,"reasoning_tokens":0}}},{"type":"tool_result","data":{"loop_id":"lup_960347f4f796126a9cc17809e53094a4","request_index":0,"call_id":"legacy-subagent-call","tool_name":"subagent","outcome":"success","output":{"content":"historical child result"}}}],"usage":{"input_tokens":1,"output_tokens":2,"reasoning_tokens":0},"requests":1,"tool_rounds":1,"final_config_revision":0,"completed_at":"2026-01-02T03:04:05.000Z"}"#;

const AUX_RECORD_JSON: &str = r#"{"version":1,"tool_ref":{"session_id":"ses_2a24b985622325826b336d25e6750499","loop_id":"lup_960347f4f796126a9cc17809e53094a4","request_index":0,"tool_call_id":"legacy-subagent-call"},"name":"subagent","subject":{"kind":"other"},"subject_truncated":false,"state":"succeeded","phase":null,"started_at":null,"finished_at":"2026-01-02T03:04:05.000Z","outcome":"success","input":{"total_bytes":0,"seen":false,"truncated":false,"expired":false,"file_bytes":0,"file_sha256":null},"result":{"total_bytes":23,"seen":true,"truncated":false,"expired":false,"file_bytes":23,"file_sha256":"345dc9f017ddf9d37ddb4b405b834fb44f93136bd9f61b98ca838400f276e7f7"},"stdout":{"start_offset":0,"observed_end":0,"seen":false,"complete":false,"truncated":false,"expired":false,"file_bytes":0,"file_sha256":null},"stderr":{"start_offset":0,"observed_end":0,"seen":false,"complete":false,"truncated":false,"expired":false,"file_bytes":0,"file_sha256":null},"command":null,"file_change":null}"#;

struct Fixture(PathBuf);
impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

async fn call(process: &mut RpcProcess, method: &str, params: Value) -> Value {
    process.send("query", method, params).await;
    let response = process.response("query").await;
    assert!(response.get("error").is_none(), "{method}: {response}");
    response["result"].clone()
}

fn done() -> Value {
    json!({"type":"response.completed", "response":{"status":"completed"}})
}

fn write_config(fixture: &Fixture, base_url: &str) -> PathBuf {
    let config = fixture.0.join("agent.toml");
    std::fs::write(
        &config,
        format!(
            r#"data_dir = {:?}
default_profile = "test"
event_capacity = 256
[profiles.test]
model = "test"
reasoning = "auto"
system_prompt = "E2E-C fixture."
tools = ["read"]
max_tool_rounds = 4
approval = "auto"
[models.test]
provider = "open_ai_responses"
model = "fixture"
base_url = "{base_url}"
api_key_env = "{KEY_ENV}"
physical_context_window = 100000
output_budget_tokens = 1000
safety_margin_tokens = 1000
supported_reasoning = ["auto"]
supports_tools = true
request_timeout_seconds = 5
"#,
            fixture.0.join("data"),
        ),
    )
    .unwrap();
    config
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn legacy_six_tool_session_is_readable_but_never_executed() {
    let fixture =
        Fixture(std::env::temp_dir().join(format!("minicore-e2e-c-{}", std::process::id())));
    let _ = std::fs::remove_dir_all(&fixture.0);
    let data_dir = fixture.0.join("data");
    let workspace = fixture.0.join("workspace");
    std::fs::create_dir_all(&workspace).unwrap();
    let canonical = std::fs::canonicalize(&workspace).unwrap();

    // Lay down the authentic legacy Session, history, and auxiliary record.
    let session_dir = data_dir.join("sessions").join(SESSION_ID);
    std::fs::create_dir_all(&session_dir).unwrap();
    std::fs::write(
        session_dir.join("session.json"),
        SESSION_JSON_TEMPLATE
            .replace("__SESSION__", SESSION_ID)
            .replace("__WORKSPACE__", canonical.to_str().unwrap()),
    )
    .unwrap();
    std::fs::write(
        session_dir.join("history.jsonl"),
        format!("{HISTORY_JSONL}\n"),
    )
    .unwrap();
    let aux_dir = session_dir.join("tools").join(AUX_HASH);
    std::fs::create_dir_all(&aux_dir).unwrap();
    std::fs::write(aux_dir.join("record.json"), AUX_RECORD_JSON).unwrap();
    std::fs::write(aux_dir.join("result.bin"), b"historical child result").unwrap();

    let before_session = std::fs::read(session_dir.join("session.json")).unwrap();
    let before_history = std::fs::read(session_dir.join("history.jsonl")).unwrap();
    let before_aux_record = std::fs::read(aux_dir.join("record.json")).unwrap();
    let before_aux_result = std::fs::read(aux_dir.join("result.bin")).unwrap();

    let server = MockServer::spawn([MockResponse::sse(&[
        json!({"type":"response.output_text.delta","delta":"fresh turn"}),
        done(),
    ])])
    .await;
    let config = write_config(&fixture, server.base_url());
    let mut process = RpcProcess::spawn(&config, KEY_ENV, KEY).await;
    call(&mut process, "agent.ping", json!({})).await;

    // list/read succeed.
    let listed = call(&mut process, "session.list", json!({})).await;
    let sessions = listed["sessions"].as_array().unwrap();
    assert_eq!(sessions.len(), 1);
    assert_eq!(sessions[0]["session_id"], json!(SESSION_ID));
    let read = call(
        &mut process,
        "session.read",
        json!({"session_id":SESSION_ID,"limit":100}),
    )
    .await;
    assert_eq!(read["total"], json!(3));
    let rendered = read["items"]
        .as_array()
        .unwrap()
        .iter()
        .map(|chunk| chunk["data"].as_str().unwrap())
        .collect::<String>();
    assert!(rendered.contains("subagent"));
    assert!(rendered.contains("historical child result"));

    // turn.result reads the stored legacy exchange.
    let turn = call(
        &mut process,
        "turn.result",
        json!({"session_id":SESSION_ID,"loop_id":LOOP_ID,"limit":100,"max_bytes":4096}),
    )
    .await;
    assert_eq!(turn["availability"], json!("stored"));
    assert!(turn.to_string().contains("historical child result"));

    // tool.read/tool.output serve the legal auxiliary record through the
    // generic path.
    let tool_ref = json!({
        "session_id": SESSION_ID,
        "loop_id": LOOP_ID,
        "request_index": 0,
        "tool_call_id": TOOL_CALL_ID,
    });
    let read_tool = call(&mut process, "tool.read", tool_ref.clone()).await;
    assert_eq!(read_tool["execution"]["name"], json!("subagent"));
    let mut output_params = tool_ref;
    output_params["stream"] = json!("output");
    output_params["offset"] = json!(0);
    let output = call(&mut process, "tool.output", output_params).await;
    assert_eq!(output["encoding"], json!("utf8"));
    assert_eq!(output["data"], json!("historical child result"));

    // session.open is refused with the existing settings error, before any
    // model request or Store repair.
    process
        .send("open", "session.open", json!({"session_id":SESSION_ID}))
        .await;
    let opened = process.response("open").await;
    assert_eq!(
        opened["error"]["data"]["kind"],
        json!("invalid_session_settings")
    );

    // Bytes are unchanged.
    assert_eq!(
        std::fs::read(session_dir.join("session.json")).unwrap(),
        before_session
    );
    assert_eq!(
        std::fs::read(session_dir.join("history.jsonl")).unwrap(),
        before_history
    );
    assert_eq!(
        std::fs::read(aux_dir.join("record.json")).unwrap(),
        before_aux_record
    );
    assert_eq!(
        std::fs::read(aux_dir.join("result.bin")).unwrap(),
        before_aux_result
    );

    // A fresh five-tool Session still runs normally.
    let created = call(
        &mut process,
        "session.create",
        json!({"workspace":canonical,"profile":"test"}),
    )
    .await;
    let fresh = created["session"]["session_id"].clone();
    call(&mut process, "session.open", json!({"session_id":fresh})).await;
    let (_, wait) = process
        .send_turn_and_register_wait("fresh", &fresh, "run")
        .await;
    let waited = process.response(&wait).await;
    assert_eq!(waited["result"]["persistence"], json!("persisted"));
    assert_eq!(waited["result"]["outcome"]["type"], json!("completed"));

    let (_, stderr) = process.shutdown().await;
    assert!(!stderr.contains(KEY));
    server.finish().await;
}
